apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../minikube

patches:
  - path: linkerd-injection-patch.yaml
    target:
      kind: Deployment
      name: kitchen-service
  - path: linkerd-injection-patch.yaml
    target:
      kind: Deployment
      name: menu-service
  - path: linkerd-injection-patch.yaml
    target:
      kind: Deployment
      name: fulfillment-service
  - path: linkerd-injection-patch.yaml
    target:
      kind: Deployment
      name: kitchen-scheduler-worker
  - path: linkerd-injection-patch.yaml
    target:
      kind: Deployment
      name: station-simulator-service
