apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kitchen-service
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - dark-kitchen
  selector:
    matchLabels:
      app: kitchen-service
  endpoints:
    - port: http
      path: /metrics
      interval: 5s
