apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: dark-kitchen/kitchen-service
    newTag: local
  - name: dark-kitchen/menu-service
    newTag: local
  - name: dark-kitchen/fulfillment-service
    newTag: local
  - name: dark-kitchen/kitchen-scheduler-worker
    newTag: local
  - name: dark-kitchen/station-simulator-service
    newTag: local
