global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "kitchen-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["kitchen-service:8000"]

  - job_name: "menu-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["menu-service:8000"]

  - job_name: "fulfillment-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["fulfillment-service:8000"]

  - job_name: "station-simulator-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["station-simulator-service:8000"]

  - job_name: "kitchen-scheduler-worker"
    metrics_path: /metrics
    static_configs:
      - targets: ["kitchen-scheduler-worker:9090"]
