apiVersion: v1
kind: Service
metadata:
  name: fulfillment-service
  labels:
    app: fulfillment-service
spec:
  selector:
    app: fulfillment-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
